### ISSUE TITLE
Aliases for Slack

### ISSUE THREAD

**Issue by mmihir82** [StackStorm-Exchange/stackstorm-netbox#19] opened 2021-07-31 07:49 UTC
Hi, Can you show example of aliases, If I want to ran thru slack channel and send to stackstorm. Below I tried creating the aliases, but seems not working. Can you suggest anything?
```
---
name: "nb_check_serial"
pack: "netbox"
action_ref: "netbox.get.dcim.devices"
description: "Netbox Search by Serial"
formats:
  - display: "netbox check serial <serial>"
    representation:
      - "{{ serial }}"
ack:
  format: "Executing - Device Serial: `{{execution.parameters.serial}}` ID: `{{ execution.id }}`"
  append_url: false
result:
  format: >
     *{{execution.parameters.serial}}*
     {% if execution.result.stderr -%}
     ```{{ execution.result.stderr }}```
     {%- else -%}```{{ execution.result.stdout }}``` {~}{~} {%- endif -%}
  ```

**Comment by amanda11** [comment] 2021-07-31 11:16
Looking at the example I would say the problem is the representation, as it doesn't start with the keyword.

The representation is the string or refer that Hubot would match against.

So in the display help you state:

netbox check serial <serial>

But then your representation is just the serial device. So that is saying that to initiate the alias that you just want to send the serial device and no keyword.

Perhaps try following as the representation:

netbox check serial {{serial}}

**Comment by amanda11** [comment] 2021-07-31 11:17
Take a look also at https://docs.stackstorm.com/chatops/aliases.html as I think for your example you don't necessarily need the separate display and representation strings.

**Comment by nzlosh** [comment] 2022-01-01 21:18
Closing this issue as it is not a netbox pack issue but a general chatops question and has been addressed by amanda11

**Closed as completed by nzlosh** 2022-01-01 21:18 UTC
